apiversion: apps/v1
kind: Deployment
metadata:
  name: kubedemoapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubedemoapp
  template:
    metadata:
      lables:
        app: kubedemoapp
    spec:
      containers:
        - name: kubedemoapp
          image: fazilabegum/sample:kubedemoapp
          ports:

            - containerPort: 5000
